### ISSUE TITLE
uninitialized constant Phlex::View (NameError)

### ISSUE THREAD

**Issue by georgekettle** [nejdetkadir/phlex-heroicons#4]
Hi Nejdet!

Firstly, thanks so much for creating this! It's exactly what I'm looking for.

I just tried to install the gem on a rails app using phlex-rails gem and got this issue. I'm not sure how to solve it and was wondering if I could get some help 🙏

I've included the error below and also the relevant code I have added. Let me know if you need more info.

**Error:**

```
phlex-components-library git:(phlex-heroicons) ✗ rails s
/Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons/base.rb:6:in `<module:Heroicons>': uninitialized constant Phlex::View (NameError)

    class Base < Phlex::View
                      ^^^^^^
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons/base.rb:5:in `<module:Phlex>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons/base.rb:4:in `<main>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons.rb:10:in `require_relative'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons.rb:10:in `<module:Heroicons>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons.rb:9:in `<module:Phlex>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/phlex-heroicons-1.0.0/lib/phlex/heroicons.rb:8:in `<main>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:73:in `rescue in block in require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:51:in `block in require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
	from /Users/georgekettle/code/georgekettle/phlex-components-library/config/application.rb:7:in `<main>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:`in` `dispatch'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ./bin/rails:4:in `<main>'
/Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- phlex-heroicons (LoadError)
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
	from /Users/georgekettle/code/georgekettle/phlex-components-library/config/application.rb:7:in `<main>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/georgekettle/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ./bin/rails:4:in `<main>'
```
	
**config/initializers/phlex_heroicons.rb**

```
Phlex::Heroicons.configure do |config|
  config.default_class = 'h-4 w-4'
  config.default_variant = :solid
end
```

**Gemfile**

```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"

end

gem "phlex-rails"
gem 'phlex-heroicons'
```

**Comment by vicentereig** [comment]
@georgekettle That was fixed back in https://github.com/nejdetkadir/phlex-heroicons/pull/3 - however the new gem version never made it to rubygems. You can use straight up master from your `Gemfile` to get it to work.

```ruby
gem 'phlex-heroicons', github: 'nejdetkadir/phlex-heroicons'
```

**Comment by georgekettle** [comment]
Perfect! I will give this a go. Thanks for getting back to me ☺️Sent from my iPhoneOn 17 Dec 2023, at 5:21 am, Vicente Reig ***@***.***> wrote:﻿
@georgekettle That was fixed back in #3 - however the new gem version never made it to rubygems. You can use straight up master from your Gemfile to get it to work.
gem 'phlex-heroicons', github: 'nejdetkadir/phlex-heroicons'

**Comment by vicentereig** [comment]
@nejdetkadir Since the fix is out there in the `main` branch, it may be convenient to push a new version of the gem.

**Comment by nejdetkadir** [comment]
i released https://github.com/nejdetkadir/phlex-heroicons/releases/tag/v1.1.0

**Comment by vicentereig** [comment]
Thank you, much appreciated!
